//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalClinic.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public long id { get; set; }
        public long person_id { get; set; }
        public Nullable<long> healthplan_id { get; set; }
        public string schedule { get; set; }
    }
}
