//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalClinic.Model.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class databaseEntities : DbContext
    {
        public databaseEntities()
            : base("name=databaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appointment> Appointments { get; set; }
        public virtual DbSet<Doctor_Appointment> Doctor_Appointment { get; set; }
        public virtual DbSet<Exam> Exams { get; set; }
        public virtual DbSet<Healthplan> Healthplans { get; set; }
        public virtual DbSet<Medicine> Medicines { get; set; }
        public virtual DbSet<Medicine_Prescription> Medicine_Prescription { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Person_Healthplan> Person_Healthplan { get; set; }
        public virtual DbSet<Prescription> Prescriptions { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Product_Productsale> Product_Productsale { get; set; }
        public virtual DbSet<Productsale> Productsales { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<Service_Servicesheduling> Service_Servicesheduling { get; set; }
        public virtual DbSet<Servicescheduling> Serviceschedulings { get; set; }
        public virtual DbSet<Specialization> Specializations { get; set; }
    }
}
