//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalClinic.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_Servicesheduling
    {
        public long id { get; set; }
        public long service_id { get; set; }
        public long servicescheduling_id { get; set; }
    }
}
